version: 2

sources:
    - name: target_fact
      schema: fact
      tables:
        - name: fact_rentals
        - name: fact_rentals_tmp

    - name: stg
      schema: stg
      tables:
        - name: z_refresh_from
        - name: cust
          identifier: customer
        - name: address
        - name: city
        - name: country
        - name: film
        - name: rental
        - name: film_category
        - name: category
        - name: language
        - name: staff
        - name: store
        - name: inventory
        - name: payment
